<?php
/**
 * Created by PhpStorm.
 * User: imdante
 * Date: 2018/4/1
 * Time: 21:55
 */

namespace app\api\controller;

use think\Controller;
use think\facade\Request;
use think\facade\Session;

/**
 * api接口验证 token前置
 * api模块下 所有controller继承此类 并且验证
 * Class Authorize
 * @package app\api\controller
 */
class Authorize extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $token = Request::get('token');
        $apiToken = Session::get('apiToken');
        if(!$token){
            die('参数错误，请检查重试');
        }
        if($token != $apiToken){
           die('api调用凭据错误，请勿非法请求');
        }
    }
}