<?php
/**
 * Created by PhpStorm.
 * User: imdante
 * Date: 2018/11/21
 * Time: 14:04
 */

namespace app\api\controller;


use app\fa\model\Finance;
use app\fa\model\Projects;
use think\Controller;
use think\facade\Config;
use think\facade\Request;

class V1 extends Controller
{
    protected $appid='wx589b5ec88f198ef9';
    protected $secret='d21f5559b459e07feb15355dfeb20328';

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 换取小程序session_key
     */
    public function get_code_session(){
        $code = Request::get('code','','htmlentities');
        if($code){
            $url = "https://api.weixin.qq.com/sns/jscode2session?appid=$this->appid&secret=$this->secret&js_code=$code&grant_type=authorization_code";
            $result = file_get_contents($url);
            $result = json_decode($result,true); //转换为常规数组
            $this->result($result,200,'请求成功','json');
        }else{
            $this->result('',403,'参数错误,code不能缺少');
        }
    }
    /**
     * @throws \think\exception\DbException
     */
    public function get_finance_json(){
        $finance = new Finance();
        $data = $finance->getFinancePage([],10);
        $data = $data->toArray();
        $this->result($data['data'],200,'request is ok','json');
    }

    /**
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function get_projects_json(){
        $project = new Projects();
        $data = $project->getProjectsList();
        $this->result($data,200,'request is success','json');
    }

    /**
     * @throws \think\exception\DbException
     */
    public function get_projects_page(){
        $project = new Projects();
        $data = $project->getProjectsPage('',6);
        $data = $data->toArray();
        if($data['data']){
            $this->result($data['data'],200,'request is success','json');
        }else{
            $this->result('',404,'没有更多数据了','json');
        }

    }
    public function get_projects_status(){
        $status = Config::get('projectStatus');
        $this->result($status,200,'request is success','json');
    }
}